name: Update Court Availability

on:
  schedule:
    - cron: '*/15 * * * *' # This cron expression runs the workflow every 15 minutes
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python court_availability.py

    - name: Push updates to GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Update availability"
        git push origin main
